export const SHORTCUTS = [
  { keys: 'Ctrl/Cmd + Z', label: '撤销' },
  { keys: 'Ctrl/Cmd + Shift + Z', label: '重做' },
  { keys: 'Ctrl/Cmd + C', label: '复制选中卡片' },
  { keys: 'Ctrl/Cmd + V', label: '粘贴卡片' },
  { keys: 'Ctrl/Cmd + F', label: '搜索卡片' },
  { keys: 'Ctrl/Cmd + S', label: '保存文档' },
  { keys: 'Ctrl/Cmd + O', label: '打开文档' },
  { keys: 'Ctrl/Cmd + 0', label: '缩放至 100%' },
  { keys: 'Ctrl/Cmd + 1', label: '适应画布' },
  { keys: 'Ctrl/Cmd + +', label: '放大' },
  { keys: 'Ctrl/Cmd + -', label: '缩小' },
  { keys: 'Ctrl/Cmd + Click', label: '多选切换' },
  { keys: 'Shift + Click', label: '范围多选' },
  { keys: 'Delete / Backspace', label: '删除选中' },
  { keys: 'Esc', label: '取消选择 / 关闭面板' },
  { keys: 'Space + 拖拽', label: '平移画布' },
  { keys: 'Ctrl + 滚轮', label: '缩放' },
  { keys: '?', label: '快捷键帮助' },
] as const
